version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "04:00"
    timezone: "Asia/Manila"
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "04:00"
    timezone: "Asia/Manila"
  open-pull-requests-limit: 99
